---
# tasks file for ansible-role-avahi

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create avahi_conf_dir
  file:
    path: "{{ avahi_conf_dir }}"
    state: directory

- name: Create avahi-daemon.conf
  template:
    src: avahi-daemon.conf.j2
    dest: "{{ avahi_conf_file }}"
    #validate: echo %s
  notify: Restart avahi

- name: Start avahi
  service:
    name: "{{ avahi_daemon_service }}"
    state: started
